import type { Metadata } from "next";
import { Oxygen, Oxygen_Mono } from "next/font/google";
import { ThemeProvider } from '@/components/theme/theme-provider';
import { Toaster } from 'sonner'

import "@/styles/globals.css";
import { ThemeToggle } from "@/components/theme/theme-toggle";

const sans = Oxygen({
  variable: "--font-oxygen-sans",
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

const mono = Oxygen_Mono({
  variable: "--font-oxygen-mono",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sans.variable} ${mono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="absolute top-2 right-2">
            <ThemeToggle />
          </div>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
